
let data,tab="general",lang="fr";const E=document.getElementById("editor-content"),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function load(){data=await fetch("./data/content.json",{cache:"no-store"}).then(r=>r.json());render()}
function field(label,path,value,type="input"){return `<div class="field"><label>${label}</label>${type==="textarea"?`<textarea data-path="${path}" rows="4">${esc(value)}</textarea>`:`<input data-path="${path}" value="${esc(value)}">`}</div>`}
function panel(title,html){E.innerHTML=`<div class="panel"><h2>${title}</h2><div class="grid">${html}</div></div>`;bind()}
function bind(){E.querySelectorAll("[data-path]").forEach(x=>x.oninput=()=>setPath(x.dataset.path,x.value))}
function setPath(path,value){let o=data,parts=path.split("."),last=parts.pop();for(let p of parts)o=o[p];o[last]=value}
function render(){let d=data[lang];
 if(tab==="general")panel("Général",field("Nom du site","site.name",data.site.name)+field("Email","site.email",data.site.email)+field("GitHub","site.github",data.site.github)+field("LinkedIn","site.linkedin",data.site.linkedin)+field("Image hero (URL ou chemin)","images.hero",data.images.hero)+field("Image À propos (URL ou chemin)","images.about",data.images.about));
 if(tab==="hero")panel("Intro — "+lang.toUpperCase(),field("Petit titre",`${lang}.hero.eyebrow`,d.hero.eyebrow)+field("Grand titre",`${lang}.hero.title`,d.hero.title,"textarea")+field("Description",`${lang}.hero.text`,d.hero.text,"textarea")+field("Bouton principal",`${lang}.hero.primary`,d.hero.primary)+field("Bouton secondaire",`${lang}.hero.secondary`,d.hero.secondary)+field("Label carte",`${lang}.hero.cardLabel`,d.hero.cardLabel)+field("Titre carte",`${lang}.hero.cardTitle`,d.hero.cardTitle)+field("Texte carte",`${lang}.hero.cardText`,d.hero.cardText,"textarea"));
 if(tab==="about")panel("À propos — "+lang.toUpperCase(),field("Petit titre",`${lang}.about.eyebrow`,d.about.eyebrow)+field("Titre",`${lang}.about.title`,d.about.title)+field("Introduction",`${lang}.about.lead`,d.about.lead,"textarea")+field("Texte",`${lang}.about.text`,d.about.text,"textarea")+field("Légende image",`${lang}.about.imageCaption`,d.about.imageCaption));
 if(tab==="contact")panel("Contact — "+lang.toUpperCase(),field("Petit titre",`${lang}.contact.eyebrow`,d.contact.eyebrow)+field("Titre",`${lang}.contact.title`,d.contact.title)+field("Texte",`${lang}.contact.text`,d.contact.text,"textarea")+field("Bouton",`${lang}.contact.button`,d.contact.button));
 if(tab==="skills")repeatEditor("Compétences",d.skills,"skills");
 if(tab==="projects")repeatEditor("Projets",d.projects,"projects");
}
function repeatEditor(title,arr,type){let cards=arr.map((x,i)=>`<div class="repeat"><strong>${title.slice(0,-1)} ${i+1}</strong><div class="grid">${type==="skills"?field("Nom",`${lang}.${type}.${i}.name`,x.name)+field("Niveau",`${lang}.${type}.${i}.level`,x.level)+field("Description",`${lang}.${type}.${i}.description`,x.description,"textarea"):field("Titre",`${lang}.${type}.${i}.title`,x.title)+field("Catégorie",`${lang}.${type}.${i}.category`,x.category)+field("Description",`${lang}.${type}.${i}.description`,x.description,"textarea")+field("Image",`${lang}.${type}.${i}.image`,x.image)+field("Lien",`${lang}.${type}.${i}.link`,x.link)}</div><div class="row-actions"><button data-delete="${i}">Supprimer</button></div></div>`).join("");E.innerHTML=`<div class="panel"><h2>${title} — ${lang.toUpperCase()}</h2>${cards}<button class="add" id="add-item">+ Ajouter</button></div>`;bind();E.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{arr.splice(+b.dataset.delete,1);render()});document.getElementById("add-item").onclick=()=>{arr.push(type==="skills"?{name:"Nouvelle compétence",description:"Description concrète de cette compétence.",level:70}:{title:"Nouveau projet",category:"GAME PROJECT",description:"Décris ici le projet, ton rôle et ce que tu as développé.",image:"",link:"#"});render()}}
document.querySelectorAll("aside [data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("aside button").forEach(x=>x.classList.remove("active"));b.classList.add("active");tab=b.dataset.tab;render()});
document.getElementById("edit-language").onchange=e=>{lang=e.target.value;render()};
document.getElementById("export-button").onclick=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="content.json";a.click();URL.revokeObjectURL(a.href)};
document.getElementById("import-button").onclick=()=>document.getElementById("import-file").click();
document.getElementById("import-file").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{data=JSON.parse(await f.text());render()}catch{alert("Fichier JSON invalide.")}};
document.getElementById("reset-button").onclick=load;load().catch(()=>E.innerHTML="<div class='panel'>Impossible de charger content.json. Ouvre cette page via GitHub Pages ou un serveur local.</div>");
